services:
  # Django Backend with React Frontend
  - type: web
    name: dealership-fullstack
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd server && gunicorn --bind 0.0.0.0:$PORT djangoproj.wsgi:application --settings=djangoproj.production_settings"
    healthCheckPath: /djangoapp/get_dealers/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: djangoproj.production_settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: xrwvm-fullstack-developer-capstone-4q3s.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: dealership-db
          property: connectionString

databases:
  # PostgreSQL for Django
  - name: dealership-db
    databaseName: dealership
    user: dealership_user 