services:
  # Django Backend (Main Service)
  - type: web
    name: dealership-backend
    env: docker
    healthCheckPath: /djangoapp/get_dealers/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: djangoproj.settings
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  # PostgreSQL for Django
  - name: dealership-db
    databaseName: dealership
    user: dealership_user 