services:
  # Django Backend (Main Service)
  - type: web
    name: dealership-backend
    env: docker
    healthCheckPath: /djangoapp/get_dealers/
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: djangoproj.production_settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: xrwvm-fullstack-developer-capstone-4q3s.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: dealership-db
          property: connectionString

databases:
  # PostgreSQL for Django
  - name: dealership-db
    databaseName: dealership
    user: dealership_user 