# Generated by Django 4.2.7 on 2025-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_dealer_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='zip_code',
            new_name='zip',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='long',
        ),
        migrations.RemoveField(
            model_name='dealer',
            name='st',
        ),
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
